version: "3.9"
services:
  app:
    build:
      args:
        user: nando-user
        uid: 1000
      context: ./
      dockerfile: docker-compose/php/php-fpm.Dockerfile
    image: f_alve97/php-fpm
    container_name: php-fpm
    restart: unless-stopped
    environment:
      XDEBUG_CONFIG: client_host=172.28.0.1
      PHP_IDE_CONFIG: serverName=xdebug-docker
    volumes:
      - /home/nando/Sites:/var/www/Sites
    networks:
      - app-rede
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-rede

  nginx:
    build:
      context: ./
      dockerfile: docker-compose/nginx/ngnix.Dockerfile
    image: f_alve97/app-nginx
    container_name: nginx
    restart: unless-stopped
    working_dir: /var/www/Sites
    volumes:
      - /home/nando/Sites:/var/www/Sites
      - ./docker-compose/nginx/conf/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    networks:
      - app-rede
    depends_on:
      - db
      - app

networks:
  app-rede:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

volumes:
  db: